# Travis will need super user permissions
# in order to run this build.
sudo: required
services:
  - docker

before_install:
  - docker build -t artemdemo/docker-react -f Dockerfile.dev .

script:
  - docker run artemdemo/docker-react npm run test -- --coverage