version: '3'
services:
  react-app:
    build:
      # In case we have docker file with non conventional name
      # we need to specify it here
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      # exclude `node_modules` from volume mounting
      # insted will be used folder inside of the container
      - /app/node_modules
      # map every other folder to the one in the current directory
      # . - current directory on the local machine
      # /app - work directory in the container
      - .:/app
